In [1]:
import requests
import pandas as pd
import re
import time
from config import api_key,api_id

In [2]:
def cleanhtml(raw_html):
    cleanr = re.compile('<.*?>')
    cleantext = re.sub(cleanr, '', raw_html)
    return cleantext

In [3]:
def getJsonResponse(country,State,keyword,page):
    url = f'https://api.adzuna.com/v1/api/jobs/au/search/{page}?app_id={api_id}&app_key={api_key}&title_only={keyword}&location0={country}&location1={State}'
    headers = {'Content-type': 'application/json'}
    time.sleep(0.25)
    resp = requests.get(url, headers=headers).json()  
    return resp

In [4]:
searchList = [{'country':'Australia','state'  : 'Victoria','keyword': 'Data Analyst'},
              {'country':'Australia','state'  : 'Victoria','keyword': 'Data Scientist'},
              {'country':'Australia','state'  : 'Victoria','keyword': 'Data Engineer'},
              {'country':'Australia','state'  : 'Victoria','keyword': 'Data Architect'},
              {'country':'Australia','state'  : 'Victoria','keyword': 'Business Analyst'},
              {'country':'Australia','state'  : 'Victoria','keyword': 'Data Analytics'},
              {'country':'Australia','state'  : 'Victoria','keyword': 'Big Data'},
              {'country':'Australia','state'  : 'Victoria','keyword': 'Project Manager'},
              {'country':'Australia','state'  : 'Victoria','keyword': 'Project Analyst'},
              {'country':'Australia','state'  : 'Victoria','keyword': 'Analyst'},
              {'country':'Australia','state'  : 'Victoria','keyword': 'Insights Analyst'},
              {'country':'Australia','state'  : 'New South Wales','keyword': 'Data Analyst'},
              {'country':'Australia','state'  : 'New South Wales','keyword': 'Data Scientist'},
              {'country':'Australia','state'  : 'New South Wales','keyword': 'Data Engineer'},
              {'country':'Australia','state'  : 'New South Wales','keyword': 'Data Architect'},
              {'country':'Australia','state'  : 'New South Wales','keyword': 'Business Analyst'},
              {'country':'Australia','state'  : 'New South Wales','keyword': 'Data Analytics'},
              {'country':'Australia','state'  : 'New South Wales','keyword': 'Big Data'},
              {'country':'Australia','state'  : 'New South Wales','keyword': 'Project Manager'},
              {'country':'Australia','state'  : 'New South Wales','keyword': 'Project Analyst'},
              {'country':'Australia','state'  : 'New South Wales','keyword': 'Analyst'},
              {'country':'Australia','state'  : 'New South Wales','keyword': 'Insights Analyst'},              
              {'country':'Australia','state'  : 'Queensland','keyword': 'Data Analyst'},
              {'country':'Australia','state'  : 'Queensland','keyword': 'Data Scientist'},
              {'country':'Australia','state'  : 'Queensland','keyword': 'Data Engineer'},
              {'country':'Australia','state'  : 'Queensland','keyword': 'Data Architect'},
              {'country':'Australia','state'  : 'Queensland','keyword': 'Business Analyst'},
              {'country':'Australia','state'  : 'Queensland','keyword': 'Data Analytics'},
              {'country':'Australia','state'  : 'Queensland','keyword': 'Big Data'},
              {'country':'Australia','state'  : 'Queensland','keyword': 'Project Manager'},
              {'country':'Australia','state'  : 'Queensland','keyword': 'Project Analyst'},
              {'country':'Australia','state'  : 'Queensland','keyword': 'Analyst'},
              {'country':'Australia','state'  : 'Queensland','keyword': 'Insights Analyst'},               
              {'country':'Australia','state'  : 'Western Australia ','keyword': 'Data Analyst'},
              {'country':'Australia','state'  : 'Western Australia ','keyword': 'Data Scientist'},
              {'country':'Australia','state'  : 'Western Australia ','keyword': 'Data Engineer'},
              {'country':'Australia','state'  : 'Western Australia ','keyword': 'Data Architect'},
              {'country':'Australia','state'  : 'Western Australia ','keyword': 'Business Analyst'},
              {'country':'Australia','state'  : 'Western Australia ','keyword': 'Data Analytics'},
              {'country':'Australia','state'  : 'Western Australia ','keyword': 'Big Data'},
              {'country':'Australia','state'  : 'Western Australia','keyword': 'Project Manager'},
              {'country':'Australia','state'  : 'Western Australia','keyword': 'Project Analyst'},
              {'country':'Australia','state'  : 'Western Australia','keyword': 'Analyst'},
              {'country':'Australia','state'  : 'Western Australia','keyword': 'Insights Analyst'},               
              {'country':'Australia','state'  : 'South Australia','keyword': 'Data Analyst'},
              {'country':'Australia','state'  : 'South Australia','keyword': 'Data Scientist'},
              {'country':'Australia','state'  : 'South Australia','keyword': 'Data Engineer'},
              {'country':'Australia','state'  : 'South Australia','keyword': 'Data Architect'},
              {'country':'Australia','state'  : 'South Australia','keyword': 'Business Analyst'},
              {'country':'Australia','state'  : 'South Australia','keyword': 'Data  Analytics'},
              {'country':'Australia','state'  : 'South Australia','keyword': 'Big Data'},
              {'country':'Australia','state'  : 'South Australia','keyword': 'Project Manager'},
              {'country':'Australia','state'  : 'South Australia','keyword': 'Project Analyst'},
              {'country':'Australia','state'  : 'South Australia','keyword': 'Analyst'},
              {'country':'Australia','state'  : 'South Australia','keyword': 'Insights Analyst'},                
              {'country':'Australia','state'  : 'Australian Capital Territory','keyword': 'Data Analyst'},
              {'country':'Australia','state'  : 'Australian Capital Territory','keyword': 'Data Scientist'},
              {'country':'Australia','state'  : 'Australian Capital Territory','keyword': 'Data Engineer'},
              {'country':'Australia','state'  : 'Australian Capital Territory','keyword': 'Data Architect'},
              {'country':'Australia','state'  : 'Australian Capital Territory','keyword': 'Business Analyst'},
              {'country':'Australia','state'  : 'Australian Capital Territory','keyword': 'Data Analytics'},
              {'country':'Australia','state'  : 'Australian Capital Territory','keyword': 'Big Data'},
              {'country':'Australia','state'  : 'Australian Capital Territory','keyword': 'Project Manager'},
              {'country':'Australia','state'  : 'Australian Capital Territory','keyword': 'Project Analyst'},
              {'country':'Australia','state'  : 'Australian Capital Territory','keyword': 'Analyst'},
              {'country':'Australia','state'  : 'Australian Capital Territory','keyword': 'Insights Analyst'},                
              {'country':'Australia','state'  : 'Northern Territory','keyword': 'Data Analyst'},
              {'country':'Australia','state'  : 'Northern Territory','keyword': 'Data Scientist'},
              {'country':'Australia','state'  : 'Northern Territory','keyword': 'Data Engineer'},
              {'country':'Australia','state'  : 'Northern Territory','keyword': 'Data Architect'},
              {'country':'Australia','state'  : 'Northern Territory','keyword': 'Business Analyst'},
              {'country':'Australia','state'  : 'Northern Territory','keyword': 'Data Analytics'},
              {'country':'Australia','state'  : 'Northern Territory','keyword': 'Big Data'},
              {'country':'Australia','state'  : 'Northern Territory','keyword': 'Project Manager'},
              {'country':'Australia','state'  : 'Northern Territory','keyword': 'Project Analyst'},
              {'country':'Australia','state'  : 'Northern Territory','keyword': 'Analyst'},
              {'country':'Australia','state'  : 'Northern Territory','keyword': 'Insights Analyst'}               
             ]
jobList = []
for search in searchList:     
    page = 1    
    resp = getJsonResponse(search['country'],search['state'],search['keyword'],page)
    results_count = resp['count']
    loop_count = 10
    print(f'Extracting on state {search["state"]} keyword {search["keyword"]} with results {results_count}')
    while loop_count < results_count:
#         print(f'loop_count {loop_count} results_count{results_count}')
        for item in resp['results']:
            job = {}
            job['keyword'] = search["keyword"]
            if 'id' in item:  
                job['id'] =  item['id']  
            else:
                job['id'] = ''       
            if 'company' in item: 
                if 'display_name' in item['company']:
                    job['company'] = item['company']['display_name']
                else:
                    job['company'] = ''
            else:
                job['company'] = ''
            if 'contract_time' in item:  
                job['contract_time'] =  item['contract_time']   
            else:
                job['contract_time'] = ''     
            if 'contract_type' in item:  
                job['contract_type'] =  item['contract_type']   
            else:
                job['contract_type'] = ''         
            if 'latitude' in item:  
                job['latitude'] =  item['latitude']
            else:
                job['latitude'] = ''          
            if 'longitude' in item:  
                job['longitude'] =  item['longitude']
            else:
                job['longitude'] = ''  
            if 'location' in item: 
                if 'area' in item['location']:
                    job['area'] = item['location']['area']
                else:
                    job['area'] = ''                  
            if 'redirect_url' in item:  
                job['redirect_url'] =  item['redirect_url']
            else:
                job['redirect_url'] = ''          
            if 'created' in item:  
                job['created'] =  item['created']
            else:
                job['created'] = ''          
            if 'title' in item:  
                job['title'] =  cleanhtml(item['title'])   
            else:
                job['title'] = ''    
            if 'salary_min' in item:  
                job['salary_min'] =  item['salary_min']   
            else:
                job['salary_min'] = ''  
            if 'salary_max' in item:  
                job['salary_max'] =  item['salary_max']   
            else:
                job['salary_max'] = ''          

            jobList.append(job)
            loop_count = loop_count + 1

        page = page + 1        
        resp = getJsonResponse(search['country'],search['state'],search['keyword'],page)        
    
df = pd.DataFrame.from_dict(jobList)
df.head()

Extracting on state Victoria keyword Data Analyst with results 45
Extracting on state Victoria keyword Data Scientist with results 14
Extracting on state Victoria keyword Data Engineer with results 58
Extracting on state Victoria keyword Data Architect with results 13
Extracting on state Victoria keyword Business Analyst with results 112
Extracting on state Victoria keyword Data Analytics with results 9
Extracting on state Victoria keyword Big Data with results 0
Extracting on state Victoria keyword Project Manager with results 280
Extracting on state Victoria keyword Project Analyst with results 12
Extracting on state Victoria keyword Analyst with results 386
Extracting on state Victoria keyword Insights Analyst with results 6
Extracting on state New South Wales keyword Data Analyst with results 101
Extracting on state New South Wales keyword Data Scientist with results 22
Extracting on state New South Wales keyword Data Engineer with results 68
Extracting on state New South Wales keyword Data Architect with results 12
Extracting on state New South Wales keyword Business Analyst with results 329
Extracting on state New South Wales keyword Data Analytics with results 33
Extracting on state New South Wales keyword Big Data with results 15
Extracting on state New South Wales keyword Project Manager with results 391
Extracting on state New South Wales keyword Project Analyst with results 10
Extracting on state New South Wales keyword Analyst with results 940
Extracting on state New South Wales keyword Insights Analyst with results 15
Extracting on state Queensland keyword Data Analyst with results 13
Extracting on state Queensland keyword Data Scientist with results 2
Extracting on state Queensland keyword Data Engineer with results 17
Extracting on state Queensland keyword Data Architect with results 2
Extracting on state Queensland keyword Business Analyst with results 53
Extracting on state Queensland keyword Data Analytics with results 3
Extracting on state Queensland keyword Big Data with results 0
Extracting on state Queensland keyword Project Manager with results 84
Extracting on state Queensland keyword Project Analyst with results 0
Extracting on state Queensland keyword Analyst with results 152
Extracting on state Queensland keyword Insights Analyst with results 1
Extracting on state Western Australia  keyword Data Analyst with results 6
Extracting on state Western Australia  keyword Data Scientist with results 1
Extracting on state Western Australia  keyword Data Engineer with results 7
Extracting on state Western Australia  keyword Data Architect with results 3
Extracting on state Western Australia  keyword Business Analyst with results 16
Extracting on state Western Australia  keyword Data Analytics with results 5
Extracting on state Western Australia  keyword Big Data with results 0
Extracting on state Western Australia keyword Project Manager with results 55
Extracting on state Western Australia keyword Project Analyst with results 1
Extracting on state Western Australia keyword Analyst with results 72
Extracting on state Western Australia keyword Insights Analyst with results 0
Extracting on state South Australia keyword Data Analyst with results 1
Extracting on state South Australia keyword Data Scientist with results 2
Extracting on state South Australia keyword Data Engineer with results 1
Extracting on state South Australia keyword Data Architect with results 0
Extracting on state South Australia keyword Business Analyst with results 20
Extracting on state South Australia keyword Data  Analytics with results 1
Extracting on state South Australia keyword Big Data with results 0
Extracting on state South Australia keyword Project Manager with results 40
Extracting on state South Australia keyword Project Analyst with results 0
Extracting on state South Australia keyword Analyst with results 50
Extracting on state South Australia keyword Insights Analyst with results 0
Extracting on state Australian Capital Territory keyword Data Analyst with results 39
Extracting on state Australian Capital Territory keyword Data Scientist with results 11
Extracting on state Australian Capital Territory keyword Data Engineer with results 7
Extracting on state Australian Capital Territory keyword Data Architect with results 2
Extracting on state Australian Capital Territory keyword Business Analyst with results 49
Extracting on state Australian Capital Territory keyword Data Analytics with results 9
Extracting on state Australian Capital Territory keyword Big Data with results 1
Extracting on state Australian Capital Territory keyword Project Manager with results 89
Extracting on state Australian Capital Territory keyword Project Analyst with results 0
Extracting on state Australian Capital Territory keyword Analyst with results 144
Extracting on state Australian Capital Territory keyword Insights Analyst with results 1
Extracting on state Northern Territory keyword Data Analyst with results 2
Extracting on state Northern Territory keyword Data Scientist with results 0
Extracting on state Northern Territory keyword Data Engineer with results 0
Extracting on state Northern Territory keyword Data Architect with results 0
Extracting on state Northern Territory keyword Business Analyst with results 6
Extracting on state Northern Territory keyword Data Analytics with results 0
Extracting on state Northern Territory keyword Big Data with results 0
Extracting on state Northern Territory keyword Project Manager with results 17
Extracting on state Northern Territory keyword Project Analyst with results 0
Extracting on state Northern Territory keyword Analyst with results 13
Extracting on state Northern Territory keyword Insights Analyst with results 0

,keyword,id,company,contract_time,contract_type,latitude,longitude,area,redirect_url,created,title,salary_min,salary_max
0,Data Analyst,1696106373,Peoplebank,full_time,,-37.8146,144.97,"[Australia, Victoria, Melbourne Region, Melbou...",https://www.adzuna.com.au/land/ad/1696106373?s...,2020-09-10T15:56:11Z,Data Analyst,,
1,Data Analyst,1700216380,Finite Recruitment,full_time,,-37.0944,144.353,"[Australia, Victoria]",https://www.adzuna.com.au/land/ad/1700216380?s...,2020-09-12T16:34:22Z,Data Analyst,,
2,Data Analyst,1670547841,Ventia,full_time,,-37.8146,144.97,"[Australia, Victoria, Melbourne Region, Melbou...",https://www.adzuna.com.au/land/ad/1670547841?s...,2020-08-28T14:50:14Z,Graduate Estate Data Analyst,,
3,Data Analyst,1684187746,Talent International,full_time,,-37.8373,144.976,"[Australia, Victoria, Melbourne Region, Stonni...",https://www.adzuna.com.au/land/ad/1684187746?s...,2020-09-03T16:00:42Z,Business Data Analyst,100000,130000
4,Data Analyst,1684185804,Natural Selection Group,full_time,,-37.0944,144.353,"[Australia, Victoria]",https://www.adzuna.com.au/land/ad/1684185804?s...,2020-09-03T16:00:33Z,SAP Data Analyst,,

In [6]:
df = df.drop_duplicates(subset='id', keep="first")

In [7]:
df.to_csv('jobs.csv', index= False)

In [10]:
df.count

<bound method DataFrame.count of            keyword          id                        company contract_time  \
0     Data Analyst  1696106373                     Peoplebank     full_time
1     Data Analyst  1700216380             Finite Recruitment     full_time
2     Data Analyst  1670547841                         Ventia     full_time
3     Data Analyst  1684187746           Talent International     full_time
4     Data Analyst  1684185804        Natural Selection Group     full_time
...            ...         ...                            ...           ...
3585       Analyst  1646054977  Northern Territory Government     full_time
3586       Analyst  1646054990  Northern Territory Government     full_time
3587       Analyst  1658502823  Northern Territory Government     full_time
3588       Analyst  1695944109  Northern Territory Government     full_time
3589       Analyst  1651824280     Powerdata Group Consulting     full_time

     contract_type latitude longitude  \
0                  -37.8146    144.97
1                  -37.0944   144.353
2                  -37.8146    144.97
3                  -37.8373   144.976
4                  -37.0944   144.353
...            ...      ...       ...
3585      contract -15.6221   131.955
3586     permanent -15.6221   131.955
3587      contract -15.6221   131.955
3588      contract -15.6221   131.955
3589     permanent -15.6221   131.955

                                                   area  \
0     [Australia, Victoria, Melbourne Region, Melbou...
1                                 [Australia, Victoria]
2     [Australia, Victoria, Melbourne Region, Melbou...
3     [Australia, Victoria, Melbourne Region, Stonni...
4                                 [Australia, Victoria]
...                                                 ...
3585     [Australia, Northern Territory, Darwin Region]
3586     [Australia, Northern Territory, Darwin Region]
3587     [Australia, Northern Territory, Darwin Region]
3588     [Australia, Northern Territory, Darwin Region]
3589     [Australia, Northern Territory, Darwin Region]

                                           redirect_url               created  \
0     https://www.adzuna.com.au/land/ad/1696106373?s...  2020-09-10T15:56:11Z
1     https://www.adzuna.com.au/land/ad/1700216380?s...  2020-09-12T16:34:22Z
2     https://www.adzuna.com.au/land/ad/1670547841?s...  2020-08-28T14:50:14Z
3     https://www.adzuna.com.au/land/ad/1684187746?s...  2020-09-03T16:00:42Z
4     https://www.adzuna.com.au/land/ad/1684185804?s...  2020-09-03T16:00:33Z
...                                                 ...                   ...
3585  https://www.adzuna.com.au/details/1646054977?s...  2020-08-17T13:18:43Z
3586  https://www.adzuna.com.au/details/1646054990?s...  2020-08-17T13:18:49Z
3587  https://www.adzuna.com.au/details/1658502823?s...  2020-08-24T16:50:25Z
3588  https://www.adzuna.com.au/details/1695944109?s...  2020-09-10T13:36:48Z
3589  https://www.adzuna.com.au/details/1651824280?s...  2020-08-20T14:06:56Z

                                  title salary_min salary_max
0                          Data Analyst
1                          Data Analyst
2          Graduate Estate Data Analyst
3                 Business Data Analyst     100000     130000
4                      SAP Data Analyst
...                                 ...        ...        ...
3585            Senior Business Analyst
3586      Resource and Planning Analyst
3587       Activity Information Analyst
3588           Senior Technical Analyst
3589  Business Process Analyst / Writer

[2829 rows x 13 columns]>